name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.1.0
      - uses: pnpm/action-setup@v6.1.0
        with:
          version: latest
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24.15.0
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm test run
      - run: pnpm lint
      - run: pnpm build
